import os
import requests
import json
from typing import Dict, Any
from agent_core.state_manager import StateManager


class Executor:
    def __init__(self, state_manager: StateManager):
        self.state_manager = state_manager
        self.base_url = os.getenv("API_BASE_URL", "http://127.0.0.1:8000")
        # 核心：这里的 db_path 必须与物理实验中的路径一致
        self.db_path = r"E:\GeoSensing_Agent_System\data\databases\satellite_data.db"

        self.TOOL_ROUTE_MAP = {
            "get_boundary": "/get_boundary",
            "get_satellite_tle": "/get_satellite_tle",
            "get_observation_overlap": "/get_observation_overlap",
            "plan_satellite_combination": "/plan_satellite_combination"
        }

    def execute(self, action_params: Dict[str, Any], pending_snapshot: Dict[str, Any]):
        tool_name = action_params["tool_name"]
        arguments = action_params["arguments"]
        route = self.TOOL_ROUTE_MAP.get(tool_name)

        print(f"\n🔍 [Debug] 准备调用工具: {tool_name}")
        print(f"📤 [Debug] 发送的参数 (Payload): {json.dumps(arguments, ensure_ascii=False, indent=2)}")

        try:
            response = requests.post(f"{self.base_url}{route}", json=arguments, timeout=30)

            if response.status_code == 200:
                result = response.json()
                print(f"✅ [Executor] {tool_name} 执行成功！")

                # 物理层对齐：从返回的 'data' 或根节点提取结果
                raw_data = result.get("data") if "data" in result else result

                # 记录成功后的资产和履历
                new_asset_info = {
                    "semantic_tag": pending_snapshot["output_tag"],
                    "data_type": self.state_manager.TYPE_MAPPING.get(pending_snapshot["output_tag"]),
                    "value": raw_data if isinstance(raw_data, (dict, list)) else None,
                    "file_path": raw_data if isinstance(raw_data, str) else "",
                    "desc": f"Generated by {tool_name}"
                }
                self.state_manager.add_asset(new_asset_info)
                self.state_manager.record_step(pending_snapshot)
                return True

            elif response.status_code == 422:
                # 关键调试：打印 FastAPI 的具体参数报错详情
                print(f"❌ [Error 422] 参数校验失败！API 详情: {response.json().get('detail')}")
                print(f"💡 [Tip] 请检查 '{tool_name}' 的 Pydantic 模型要求，字段名或类型可能不匹配。")
                return False
            else:
                print(f"❌ [Executor] 物理调用失败，状态码: {response.status_code}")
                print(f"📝 错误响应体: {response.text}")
                return False

        except Exception as e:
            print(f"❌ [Executor] 执行异常: {str(e)}")
            return False